name: rsat-core-nobuilds
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.3.2
  - amply=0.1.5
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - atk-1.0=2.38.0
  - attmap=0.13.2
  - attrs=22.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-ctc=1.60.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-iranges=2.20.0
  - bioconductor-qvalue=2.18.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-singlecellexperiment=1.8.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - blast=2.11.0
  - boto3=1.26.65
  - botocore=1.29.65
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - clustalw=2.1
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.6
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.4
  - coincbc=2.10.8
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - cryptography=38.0.2
  - curl=7.76.1
  - cycler=0.11.0
  - d3=5.15.0
  - datrie=0.8.2
  - dbus=1.13.6
  - defusedxml=0.7.1
  - docutils=0.19
  - dpath=2.0.6
  - dropbox=11.36.0
  - entrez-direct=16.2
  - exceptiongroup=1.1.0
  - expat=2.2.10
  - filechunkio=1.8
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.1
  - ftputil=5.0.4
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.42.8
  - gettext=0.21.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - ghostscript=9.18
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.30
  - glib=2.74.1
  - glib-tools=2.74.1
  - gnuplot=5.0.3
  - google-api-core=2.11.0
  - google-api-python-client=2.76.0
  - google-auth=2.16.0
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.7.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.4.1
  - googleapis-common-protos=1.57.1
  - graphite2=1.3.13
  - graphviz=2.42.3
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.5
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - htslib=1.9
  - httplib2=0.21.0
  - humanfriendly=10.0
  - icu=67.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.10.2
  - iniconfig=2.0.0
  - jinja2=3.1.2
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_core=4.11.1
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.4.4
  - krb5=1.17.2
  - lcms2=2.14
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcrc32c=1.1.2
  - libcurl=7.76.1
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=12.2.0
  - libgd=2.2.5
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.39
  - libpq=12.3
  - libprotobuf=3.21.8
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - libxslt=1.1.33
  - libzlib=1.2.13
  - logmuse=0.2.6
  - make=4.3
  - markdown-it-py=2.1.0
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mdurl=0.1.0
  - multidict=6.0.2
  - munkres=1.0.7
  - mysql=5.7.20
  - mysql-common=8.0.32
  - mysql-connector-c=6.1.11
  - mysql-libs=8.0.32
  - nbformat=5.7.3
  - ncurses=6.3
  - nomkl=1.0
  - nspr=4.35
  - nss=3.82
  - numexpr=2.8.3
  - numpy=1.21.6
  - oauth2client=4.1.3
  - openjpeg=2.5.0
  - openssl=1.1.1s
  - packaging=23.0
  - paml=4.9
  - pandas=1.3.5
  - pango=1.42.4
  - paramiko=3.0.0
  - pcre=8.45
  - pcre2=10.40
  - peppy=0.35.4
  - perl=5.26.2
  - perl-aceperl=1.92
  - perl-algorithm-cluster=1.58
  - perl-algorithm-diff=1.1903
  - perl-algorithm-munkres=0.08
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-appconfig=1.71
  - perl-archive-tar=2.32
  - perl-array-compare=3.0.1
  - perl-autoloader=5.74
  - perl-b-hooks-endofscope=0.21
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-bigfile=1.07
  - perl-bio-coordinate=1.007001
  - perl-bio-das=1.17
  - perl-bio-db-hts=3.01
  - perl-bio-featureio=1.6.905
  - perl-bio-phylo=0.58
  - perl-bio-samtools=1.43
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.2
  - perl-bioperl-core=1.007002
  - perl-bioperl-run=1.007002
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-cache-cache=1.08
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-cgi=4.44
  - perl-class-data-inheritable=0.08
  - perl-class-inspector=1.34
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.12
  - perl-class-std=0.013
  - perl-class-std-fast=0.0.8
  - perl-clone=0.42
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-convert-binary-c=0.78
  - perl-convert-binhex=1.125
  - perl-crypt-rc4=2.02
  - perl-data-dumper=2.173
  - perl-data-optlist=0.110
  - perl-data-predicate=2.1.1
  - perl-data-stag=0.14
  - perl-date-format=2.30
  - perl-db-file=1.855
  - perl-dbd-mysql=4.046
  - perl-dbd-sqlite=1.64
  - perl-dbi=1.642
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.005
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-digest-md5-file=0.08
  - perl-digest-perl-md5=1.9
  - perl-digest-sha1=2.13
  - perl-dist-checkconflicts=0.11
  - perl-dynaloader=1.25
  - perl-email-date-format=1.005
  - perl-email-simple=2.218
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-ensembl-api=98
  - perl-ensembl-compara=98
  - perl-ensembl-core=98
  - perl-ensembl-funcgen=98
  - perl-ensembl-genomes=44
  - perl-ensembl-io=98
  - perl-ensembl-variation=98
  - perl-error=0.17027
  - perl-eval-closure=0.14
  - perl-exception-class=1.44
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-spec=3.48_01
  - perl-file-temp=0.2304
  - perl-file-which=1.23
  - perl-font-afm=1.20
  - perl-font-ttf=1.06
  - perl-gd=2.71
  - perl-getopt-long=2.50
  - perl-graph=0.9704
  - perl-graphviz=2.24
  - perl-html-element-extended=1.18
  - perl-html-entities-numbered=0.04
  - perl-html-formatter=2.16
  - perl-html-parser=3.72
  - perl-html-tableextract=2.13
  - perl-html-tagset=3.20
  - perl-html-template=2.97
  - perl-html-tidy=1.60
  - perl-html-tree=5.07
  - perl-html-treebuilder-xpath=0.14
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-http-tiny=0.076
  - perl-image-info=1.38
  - perl-image-size=3.300
  - perl-io-all=0.87
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-sessiondata=1.03
  - perl-io-socket-ssl=2.066
  - perl-io-string=1.08
  - perl-io-stringy=2.111
  - perl-io-tty=1.12
  - perl-io-zlib=1.10
  - perl-ipc-run=20180523.0
  - perl-ipc-sharelite=0.17
  - perl-jcode=2.07
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-lib=0.63
  - perl-libwww-perl=6.39
  - perl-libxml-perl=0.08
  - perl-list-compare=0.53
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lockfile-simple=0.208
  - perl-log-log4perl=1.49
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-lwp-simple=6.15
  - perl-mailtools=2.21
  - perl-math-cdf=0.1
  - perl-math-derivative=1.01
  - perl-math-random=0.72
  - perl-math-spline=0.02
  - perl-mce=1.837
  - perl-mce-shared=1.840
  - perl-mime-base64=3.15
  - perl-mime-lite=3.030
  - perl-mime-tools=5.508
  - perl-mime-types=2.17
  - perl-mldbm=2.05
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.003004
  - perl-moose=2.2011
  - perl-mozilla-ca=20180117
  - perl-mro-compat=0.13
  - perl-namespace-autoclean=0.28
  - perl-namespace-clean=0.27
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-number-format=1.75
  - perl-object-insideout=4.05
  - perl-ole-storage_lite=0.19
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-parallel-forkmanager=2.02
  - perl-params-util=1.07
  - perl-parent=0.236
  - perl-parse-recdescent=1.967015
  - perl-pathtools=3.75
  - perl-pdf-api2=2.035
  - perl-pod-escapes=1.07
  - perl-pod-usage=1.69
  - perl-posix=1.38_03
  - perl-postscript=0.06
  - perl-readonly=2.05
  - perl-rest-client=281
  - perl-role-tiny=2.000008
  - perl-scalar-list-utils=1.52
  - perl-sereal=4.007
  - perl-sereal-decoder=4.007
  - perl-sereal-encoder=4.007
  - perl-set-intervaltree=0.12
  - perl-set-scalar=1.29
  - perl-soap-lite=1.19
  - perl-socket=2.027
  - perl-sort-naturally=1.03
  - perl-spreadsheet-parseexcel=0.65
  - perl-spreadsheet-writeexcel=2.40
  - perl-statistics-descriptive=3.0702
  - perl-statistics-distributions=1.02
  - perl-storable=3.15
  - perl-string-approx=3.27
  - perl-sub-exporter=0.987
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.006003
  - perl-sub-uplevel=0.2800
  - perl-svg=2.84
  - perl-svg-graph=0.02
  - perl-task-weaken=1.06
  - perl-template-toolkit=2.26
  - perl-test=1.26
  - perl-test-deep=1.128
  - perl-test-differences=0.67
  - perl-test-exception=0.43
  - perl-test-harness=3.42
  - perl-test-leaktrace=0.16
  - perl-test-more=1.001002
  - perl-test-most=0.35
  - perl-test-requiresinternet=0.05
  - perl-test-warn=0.36
  - perl-text-csv=2.00
  - perl-text-diff=1.45
  - perl-tie-ixhash=1.23
  - perl-time-hires=1.9760
  - perl-time-local=1.28
  - perl-timedate=2.30
  - perl-tree-dag_node=1.31
  - perl-try-tiny=0.30
  - perl-type-tiny=1.004004
  - perl-types-serialiser=1.0
  - perl-unicode-map=0.112
  - perl-uri=1.76
  - perl-util-properties=0.18
  - perl-variable-magic=0.61
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-filter-buffertext=1.01
  - perl-xml-libxml=2.0132
  - perl-xml-libxslt=1.94
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44
  - perl-xml-regexp=0.04
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-sax-writer=0.57
  - perl-xml-simple=2.25
  - perl-xml-twig=3.52
  - perl-xml-writer=0.625
  - perl-xml-xpath=1.44
  - perl-xml-xpathengine=0.14
  - perl-xsloader=0.24
  - perl-yaml=1.29
  - pillow=9.2.0
  - pip=23.0
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - pluggy=1.0.0
  - ply=3.11
  - prettytable=3.6.0
  - protobuf=4.21.8
  - psutil=5.9.3
  - pthread-stubs=0.4
  - pulp=2.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.14.0
  - pygraphviz=1.7
  - pynacl=1.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-irodsclient=1.1.6
  - python_abi=3.7
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt=5.12.9
  - r-acidbase=0.1.9
  - r-amap=0.8_18
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.75.0_0
  - r-bioverbs=0.2.13
  - r-bitops=1.0_7
  - r-brew=1.0_6
  - r-brio=0.3.17
  - r-cachem=1.0.5
  - r-callr=3.7.0
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-cli=2.5.0
  - r-clipr=0.7.1
  - r-colorspace=2.0_1
  - r-commonmark=1.7
  - r-covr=3.5.1
  - r-cpp11=0.2.7
  - r-crayon=1.4.1
  - r-crosstalk=1.1.1
  - r-curl=4.3.1
  - r-data.table=1.14.0
  - r-dendextend=1.15.1
  - r-desc=1.3.0
  - r-devtools=2.4.1
  - r-diffobj=0.3.4
  - r-digest=0.6.27
  - r-dplyr=1.0.6
  - r-dt=0.18
  - r-dynamictreecut=1.63_1
  - r-egg=0.4.5
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-flux=0.3_0
  - r-forcats=0.5.1
  - r-foreign=0.8_76
  - r-formatr=1.9
  - r-fs=1.5.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gdata=2.18.0
  - r-generics=0.1.0
  - r-ggplot2=3.3.3
  - r-gh=1.3.0
  - r-git2r=0.28.0
  - r-gitcreds=0.1.1
  - r-glue=1.4.2
  - r-goalie=0.4.4
  - r-gplots=3.1.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-haven=2.4.1
  - r-highr=0.9
  - r-hms=1.1.0
  - r-htmltools=0.5.1.1
  - r-htmlwidgets=1.5.3
  - r-httr=1.4.2
  - r-ini=0.3.1
  - r-isoband=0.2.4
  - r-jpeg=0.1_8.1
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_18
  - r-knitr=1.33
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-later=1.2.0
  - r-lattice=0.20_44
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.0
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.3_3
  - r-matrixstats=0.58.0
  - r-memoise=2.0.0
  - r-mgcv=1.8_35
  - r-mime=0.10
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-openssl=1.4.4
  - r-openxlsx=4.2.3
  - r-pillar=1.6.1
  - r-pkgbuild=1.2.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.1
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-promises=1.2.0.1
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r.methodss3=1.8.1
  - r-r.oo=1.24.0
  - r-r.utils=2.10.1
  - r-r6=2.5.0
  - r-rcmdcheck=1.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rcurl=1.98_1.3
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.3.0
  - r-reshape2=1.4.4
  - r-rex=1.2.0
  - r-rio=0.5.26
  - r-rjsonio=1.3_1.4
  - r-rlang=0.4.11
  - r-roxygen2=7.1.1
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-rversions=2.0.2
  - r-scales=1.1.1
  - r-sessioninfo=1.1.1
  - r-snow=0.4_3
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-sys=3.4
  - r-testthat=3.0.2
  - r-tibble=3.1.2
  - r-tidyselect=1.1.1
  - r-transformer=0.2.12
  - r-usethis=1.6.3
  - r-utf8=1.2.1
  - r-vctrs=0.3.8
  - r-viridis=0.6.1
  - r-viridislite=0.4.0
  - r-waldo=0.2.5
  - r-whisker=0.4
  - r-withr=2.4.2
  - r-xfun=0.23
  - r-xml=3.99_0.3
  - r-xml2=1.3.2
  - r-xopen=1.0.0
  - r-yaml=2.2.1
  - r-zip=2.1.1
  - r-zoo=1.8_9
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.2
  - reretry=0.11.8
  - rich=13.3.1
  - rsa=4.9
  - rsat-core=2020.02.29
  - s3transfer=0.6.0
  - scipy=1.5.3
  - sed=4.8
  - seqlogo=5.29.8
  - setuptools=67.1.0
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.3.0
  - smmap=3.0.5
  - snakemake=7.21.0
  - snakemake-minimal=7.21.0
  - sqlite=3.40.0
  - stone=3.3.1
  - stopit=1.1.2
  - sysroot_linux-64=2.12
  - t_coffee=11.0.8
  - tabulate=0.9.0
  - throttler=1.2.1
  - tidyp=1.04
  - tk=8.6.12
  - tktable=2.10
  - tomli=2.0.1
  - toposort=1.7
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ubiquerg=0.6.2
  - unicodedata2=14.0.0
  - uritemplate=4.1.1
  - urllib3=1.26.14
  - veracitools=0.1.3
  - vmatch=2.3.0
  - wcwidth=0.2.6
  - weblogo=3.7.9
  - wget=1.20.3
  - wheel=0.38.4
  - wrapt=1.14.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - yte=1.5.1
  - zipp=3.12.1
  - zlib=1.2.13
  - zstd=1.5.2
